[package]
name = "bergshamra-enc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
rust-version.workspace = true
description = "XML Encryption for Bergshamra XML Security library"

[features]
default = ["rustcrypto", "legacy-algorithms", "post-quantum", "pkcs11"]
rustcrypto = ["bergshamra-crypto/rustcrypto", "bergshamra-keys/rustcrypto", "bergshamra-transforms/rustcrypto", "kryptering/rustcrypto"]
aws-lc = ["bergshamra-crypto/aws-lc", "bergshamra-keys/aws-lc", "bergshamra-transforms/aws-lc", "kryptering/aws-lc"]
fips = ["aws-lc", "bergshamra-crypto/fips", "bergshamra-keys/fips", "bergshamra-transforms/fips", "kryptering/fips"]
legacy-algorithms = ["bergshamra-crypto/legacy-algorithms", "bergshamra-keys/legacy-algorithms", "bergshamra-transforms/legacy-algorithms", "kryptering/legacy"]
post-quantum = ["bergshamra-crypto/post-quantum", "bergshamra-keys/post-quantum", "bergshamra-transforms/post-quantum", "kryptering/post-quantum"]
pkcs11 = ["bergshamra-crypto/pkcs11", "bergshamra-keys/pkcs11", "bergshamra-transforms/pkcs11", "kryptering/pkcs11"]

[dependencies]
bergshamra-core.workspace = true
bergshamra-xml.workspace = true
bergshamra-transforms.workspace = true
bergshamra-keys.workspace = true
bergshamra-c14n.workspace = true
bergshamra-crypto.workspace = true
base64.workspace = true
uppsala.workspace = true
kryptering.workspace = true
